---

- name: Add granted domains
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "granted_domains_{{stack}}.yml"
      skip: true
  tags: [always]


- name: Add revoked domains
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "revoked_domains_{{stack}}.yml"
      skip: true
  tags: [always]



- import_tasks: grant/azure_rg.yml
  tags:
    - init
    - common
    - grantdomain
    - revokedomain


- import_tasks: grant/azure_lb.yml
  tags:
    - init
    - common
    - grantdomain
    - revokedomain

- import_tasks: grant/azure_sg.yml
  tags:
    - init
    - common
    - grantdomain
    - revokedomain

- import_tasks: init/ssl.yml
  tags: 
   - init
   - common

