---

- name:  Remove domain configuration files from nginx directory
  file:
    path: "/usr/local/nginx/conf/sites/{{item.domain}}.conf"
    state: absent
  when:
    - revoked_domains is defined
    - ( revoked_domains )
  with_items: 
    - "{{ revoked_domains }}"
  notify: Reload nginx daemon
